version: 0.0
os: linux

files:
  - source: ./build/libs/CloudAssignment2-0.0.1-SNAPSHOT.war
    destination: /home/centos
  - source: ./cloudwatch-config.json
    destination: /home/centos

hooks:
  ApplicationStop:
   - location: ./codedeploy/appStop.sh
     timeout: 180
     runas: centos
  BeforeInstall:
   - location: ./codedeploy/beforeInstall.sh
     timeout: 180
     runas: centos
  AfterInstall:
   - location: ./codedeploy/afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./codedeploy/appStart.sh
     timeout: 180
     runas: centos