version: 2
jobs:
  build:
    branches:
      only:
        - Assignment7
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install Package requirements
          command: |
            sudo apt-get install epel-release && sudo apt-get install statsd
            sudo apt-get update && sudo apt-get install wget zip unzip -y
            sudo apt-get install -y python3-pip
            sudo pip3 install awscli
      - run:
          name: Build WAR
          command: |
            cd webapp/CloudAssignment2
            rm -rf build
            chmod +x gradlew
            ./gradlew clean build
      - run:
          name: Build Deployment Artifacts
          command: |
            mkdir artifacts
            chmod 777 artifacts
            zip -r csye6225-webapp-${CIRCLE_BUILD_NUM}.zip ./infrastructure/aws/codedeploy/*.sh webapp/CloudAssignment2/build/libs/CloudAssignment2-0.0.1-SNAPSHOT.war ./infrastructure/aws/appspec.yml
            pwd
            ls -al
            mv csye6225-webapp-${CIRCLE_BUILD_NUM}.zip artifacts/
            cd artifacts    
            ls -al 
      - run:
          name: Upload ZIP to S3 bucket
          command: aws s3 cp artifacts/csye6225-webapp-${CIRCLE_BUILD_NUM}.zip s3://codedeploy.${DOMAIN_NAME}/csye6225-webapp-${CIRCLE_BUILD_NUM}.zip
      - run:
          name: Configure cloudwatch
          command: sudo /home/centos/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/cloudwatch-config.json -s
      - run:
          name: Create Deployment
          command: aws deploy create-deployment --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name csye6225-webapp-deployment --description "CSYE6225 - Codedeploy" --region=${AWS_REGION} --s3-location bucket=codedeploy.${DOMAIN_NAME},bundleType=zip,key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip
